on: [ push ]
permissions:
  contents: write
  id-token: write


jobs:
  # Always at the @latest version on a main branch push
#  latest-tag:
#    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/main'
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Bump version and push tag
#        id: tag
#        uses: mathieudutour/github-tag-action@v5.6
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#
#          custom_tag: latest

  test-tag:
    runs-on: ubuntu-latest
#    needs: [ latest-tag ]
    name: A job to test my new action
    steps:
      - name: Add the tag
        id: tag-me
        uses: otivo-labs/tag-repo-next-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          env-slug: 'test-1'
          date: '2021-08-01'

      - name: Get the output time
        run: echo "The time was ${{ steps.tag-me.outputs.nextTag }}"