on: [push]

jobs:
  test_tag:
    runs-on: ubuntu-latest
    name: A job to test my new action
    steps:
      - name: Add the tag
        id: tag-me
        uses: otivo-labs/tag-repo-next-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          env-slug: 'test-1'
          date: '2021-08-01'
  
      - name: Get the output time
        run: echo "The time was ${{ steps.tag-me.outputs.nextTag }}"