on: [ push ]
permissions:
  contents: write
  id-token: write


jobs:
  test-tag:
    runs-on: ubuntu-latest
    name: A job to test my new action
    steps:
      - name: Add the tag
        id: tag-me
        uses: otivo-labs/tag-repo-next-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          env-slug: 'test-1'

      - name: Get the output time
        run: echo "The time was ${{ steps.tag-me.outputs.nextTag }}"